/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DECL = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int ASSOC = 7;
  /** RegularExpression Id. */
  int RefAssoc = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int Num = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int TIMES = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int BIGGER = 17;
  /** RegularExpression Id. */
  int SMALLER = 18;
  /** RegularExpression Id. */
  int EQUALS = 19;
  /** RegularExpression Id. */
  int DIF = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int EL = 23;
  /** RegularExpression Id. */
  int VAR = 24;
  /** RegularExpression Id. */
  int Id = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"decl\"",
    "\"in\"",
    "\"end\"",
    "\"=\"",
    "\":=\"",
    "<BOOL>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"\\n\"",
    "\"var\"",
    "<Id>",
  };

}
