/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DECL = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int ASSOC = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int RefAssoc = 13;
  /** RegularExpression Id. */
  int TWOEXPR = 14;
  /** RegularExpression Id. */
  int BOOL = 15;
  /** RegularExpression Id. */
  int Num = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int TIMES = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int LPAR = 21;
  /** RegularExpression Id. */
  int RPAR = 22;
  /** RegularExpression Id. */
  int BIGGER = 23;
  /** RegularExpression Id. */
  int SMALLER = 24;
  /** RegularExpression Id. */
  int EQUALS = 25;
  /** RegularExpression Id. */
  int DIF = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int EL = 29;
  /** RegularExpression Id. */
  int FUN = 30;
  /** RegularExpression Id. */
  int ARROW = 31;
  /** RegularExpression Id. */
  int ARROWT = 32;
  /** RegularExpression Id. */
  int INT = 33;
  /** RegularExpression Id. */
  int BOOLEAN = 34;
  /** RegularExpression Id. */
  int REF = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int VAR = 37;
  /** RegularExpression Id. */
  int Id = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"decl\"",
    "\"in\"",
    "\"end\"",
    "\"while\"",
    "\"do\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\":=\"",
    "\";\"",
    "<BOOL>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"\\n\"",
    "\"fun\"",
    "\"=>\"",
    "\"->\"",
    "\"int\"",
    "\"bool\"",
    "\"ref\"",
    "\":\"",
    "\"var\"",
    "<Id>",
  };

}
